<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>0411_256px.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="0411_256px.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="credits.html" />
    <Resource Include="help.html" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PcmLibrary\PcmLibrary.csproj" />
    <ProjectReference Include="..\PcmLibraryWindowsApi\PcmLibraryWindowsApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Windows.Forms.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
