<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-windows10.0.26100.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PcmHacking</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InTheHand.Net.Bluetooth" />
    <PackageReference Include="Tmds.DBus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PcmLibrary\PcmLibrary.csproj" />
  </ItemGroup>

</Project>
