<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>0411_256px.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="0411_256px.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="credits.html" />
    <Resource Include="help.html" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="J2534DotNet">
      <HintPath>..\..\..\PcmLibraryWindowsApi\bin\Debug\net10.0-windows\J2534DotNet.dll</HintPath>
    </Reference>
    <Reference Include="PcmLibrary">
      <HintPath>..\..\..\PcmLibrary\bin\Debug\netstandard2.0\PcmLibrary.dll</HintPath>
    </Reference>
    <Reference Include="PcmLibraryWindowsApi">
      <HintPath>..\..\..\PcmLibraryWindowsApi\bin\Debug\net10.0-windows\PcmLibraryWindowsApi.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
