<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net10.0-windows</TargetFrameworks>
    <RootNamespace>PcmLibraryWindowsApi</RootNamespace>
    <AssemblyName>PcmLibraryWindowsApi</AssemblyName>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="InTheHand.Net.Bluetooth" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="System.Management" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PcmLibrary\PcmLibrary.csproj" />
    <ProjectReference Include="..\J2534DotNet\J2534DotNet\J2534DotNet.csproj" />
  </ItemGroup>

</Project>
