; PCM Hammer - Inno Setup installer script
; Requires Inno Setup 6.x  (https://jrsoftware.org/isinfo.php)
;
; Build (from the repo root):
;   iscc Apps\installer\pcmhammer-setup.iss
;
; The payload is taken from a staging layout (see WinFormsRoot / CliRoot below).
; In CI those folders are produced by the build job. For a local build use
; Apps\installer\build-installer.ps1, which stages from each project's bin\Release
; and then invokes this script.
;
; Overridable defines (pass with iscc /D<name>=<value>):
;   AppVersion     version shown in Add/Remove Programs (default 0.0.0)
;   WinFormsRoot   folder containing PcmHammer\, PcmLogger\, VpwExplorer\
;   CliRoot        folder containing pcmhammer-cli.exe

#ifndef AppVersion
  #define AppVersion "0.0.0"
#endif

; Defaults match the CI staging layout (TemporaryArtifactStorage at the repo root).
; Paths are relative to this .iss file (Apps\installer).
#ifndef WinFormsRoot
  #define WinFormsRoot "..\..\TemporaryArtifactStorage\WinForms"
#endif
#ifndef CliRoot
  #define CliRoot "..\..\TemporaryArtifactStorage\CLI"
#endif

; Output filename (without extension) and folder. The build scripts set SetupName to
; e.g. PCMHammer_1.2.3.4 (release) or PCMHammer_YYYYMMDD_HHMMSS (dev), and OutDir to dist.
#ifndef SetupName
  #define SetupName "setup"
#endif
#ifndef OutDir
  #define OutDir "output"
#endif

#define AppName      "PCM Hammer"
#define AppPublisher "PCMHacking.net"
#define AppURL       "https://pcmhacking.net"
#define AppIcon      "..\UI\WindowsForms\PcmHammer\0411_256px.ico"

[Setup]
; AppId uniquely identifies the product for upgrades/uninstall - do not change it
; between releases or upgrades will install side-by-side instead of replacing.
AppId={{6E3D2F1A-9C4B-4E7A-9D2E-7A1B5C9F0E22}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}

; Default install location: Program Files\PcmHammer (privileged; requires admin).
DefaultDirName={autopf}\PcmHammer
DefaultGroupName=PCM Hammer
DisableProgramGroupPage=auto
AllowNoIcons=yes

PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible

; Produces <OutDir>\<SetupName>.exe
OutputDir={#OutDir}
OutputBaseFilename={#SetupName}
SetupIconFile={#AppIcon}
; Wizard graphics use the PCM Hammer logo (generated by make-wizard-images.ps1)
; instead of the default Inno "box + CD" images.
WizardImageFile=WizardImage.png
WizardSmallImageFile=WizardSmallImage.png
UninstallDisplayIcon={app}\PcmHammer\PcmHammer.exe
UninstallDisplayName={#AppName}

Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
CloseApplications=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Types]
Name: "standard"; Description: "Standard (PCM Hammer, PCM Logger, command-line tool)"
Name: "full";     Description: "Full (also installs VPW Explorer)"
Name: "cli";      Description: "Command-line tool only"
Name: "custom";   Description: "Custom installation"; Flags: iscustom

[Components]
; Each app is selectable on its own. VPW Explorer is only in the "full" type, so it is
; unchecked by default (the default type is the first one, "standard").
Name: "pcmhammer";   Description: "PCM Hammer";                            Types: standard full
Name: "pcmlogger";   Description: "PCM Logger";                            Types: standard full
Name: "vpwexplorer"; Description: "VPW Explorer";                          Types: full
Name: "cli";         Description: "Command-line tool (pcmhammer-cli.exe)"; Types: standard full cli

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut for PCM Hammer"; GroupDescription: "Additional icons:"; Components: pcmhammer

[Files]
; --- GUI applications (each in its own subfolder; kernels live with PcmHammer) ---
Source: "{#WinFormsRoot}\PcmHammer\*";   DestDir: "{app}\PcmHammer";   Components: pcmhammer;   Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#WinFormsRoot}\PcmLogger\*";   DestDir: "{app}\PcmLogger";   Components: pcmlogger;   Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#WinFormsRoot}\VpwExplorer\*"; DestDir: "{app}\VpwExplorer"; Components: vpwexplorer; Flags: ignoreversion recursesubdirs createallsubdirs

; --- Command-line tool ---
Source: "{#CliRoot}\pcmhammer-cli.exe"; DestDir: "{app}\Cli"; Components: cli; Flags: ignoreversion
; The CLI loads kernels from disk (default: its working directory). Ship the kernels
; next to it so it works out of the box from {app}\Cli.
Source: "{#WinFormsRoot}\PcmHammer\Kernel-*.bin"; DestDir: "{app}\Cli"; Components: cli; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#WinFormsRoot}\PcmHammer\Loader-*.bin"; DestDir: "{app}\Cli"; Components: cli; Flags: ignoreversion skipifsourcedoesntexist

; --- Shared shortcut icon ---
Source: "{#AppIcon}"; DestDir: "{app}"; DestName: "pcmhammer.ico"; Flags: ignoreversion

[Icons]
Name: "{group}\PCM Hammer";   Filename: "{app}\PcmHammer\PcmHammer.exe";     IconFilename: "{app}\pcmhammer.ico"; Components: pcmhammer
Name: "{group}\PCM Logger";   Filename: "{app}\PcmLogger\PcmLogger.exe";     IconFilename: "{app}\pcmhammer.ico"; Components: pcmlogger
Name: "{group}\VPW Explorer"; Filename: "{app}\VpwExplorer\VpwExplorer.exe"; IconFilename: "{app}\pcmhammer.ico"; Components: vpwexplorer
Name: "{group}\Uninstall PCM Hammer"; Filename: "{uninstallexe}"
Name: "{autodesktop}\PCM Hammer"; Filename: "{app}\PcmHammer\PcmHammer.exe"; IconFilename: "{app}\pcmhammer.ico"; Tasks: desktopicon; Components: pcmhammer

[Run]
Filename: "{app}\PcmHammer\PcmHammer.exe"; Description: "Launch PCM Hammer"; Flags: nowait postinstall skipifsilent; Components: pcmhammer

[UninstallDelete]
; Remove the install tree if empty after uninstall. (Per-user settings live in
; %LOCALAPPDATA% and are intentionally left in place.)
Type: dirifempty; Name: "{app}\PcmHammer"
Type: dirifempty; Name: "{app}\PcmLogger"
Type: dirifempty; Name: "{app}\VpwExplorer"
Type: dirifempty; Name: "{app}\Cli"
Type: dirifempty; Name: "{app}"

[Code]
procedure InitializeWizard();
var
  Delta: Integer;
begin
  { Hide the "Select Setup Type" dropdown and show only the component checkboxes.
    The first type ("standard") still defines the default selection, so VPW Explorer
    stays unchecked by default while the user can freely tick/untick each app. }
  Delta := WizardForm.ComponentsList.Top - WizardForm.TypesCombo.Top;
  WizardForm.TypesCombo.Visible := False;
  WizardForm.ComponentsList.Top := WizardForm.TypesCombo.Top;
  WizardForm.ComponentsList.Height := WizardForm.ComponentsList.Height + Delta;
end;
