#
# Original works by ddub07 <github.com>
# 2023-01-03 - GampyG28 <github.com> major overhaul, renamed and updated.
# 2023-04-16 - GampyG28 <github.com> Added Assembly Kernels and Loaders
# 2023-07-16 - GampyG28 <github.com> Removed C Kernel builds
# 2024-09-05 - Antus <pcmhacking.net> Update actions
# 2025-11-09 - Antus <pcmhacking.net> Add P05
# 2025-11-16 - Antus <pcmhacking.net> Add P11
#
name: CheckBuild

on: [ pull_request, push ]

jobs:

  Kernels:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Update Package Repository
      run: sudo apt-get update

    - name: Install GNU m68k Compiler and Make tool
      run: sudo apt-get install -y gcc-m68k-linux-gnu make

    - name: Create temporary artifact storage
      run: mkdir TemporaryArtifactStorage

    - name: Build C Kernels
      run: |
        cd Kernels
        #
        # The following loop is the one location that needs to be updated when adding a new C kernel.
        #
        for p in "P12 FF2000"; do
          pcm=${p%% *}
          address=${p##* }

          echo Building Kernel ":    ${pcm}"
          make -f makefile PREFIX=/usr/bin/m68k-linux-gnu- pcm=${pcm} address=${address}
          echo "    Copy-Item Kernel-${pcm}.bin to TemporaryArtifactStorage"
          cp Kernel-${pcm}.bin ../TemporaryArtifactStorage/
          echo "    Cleanup after Kernel-${pcm}"
          echo
          make clean
        done

    - name: Build Assembly Kernels and Loaders
      run: |
        cd Kernels
        #
        # Each group is required to have 3 elements in the following order
        # 1: PCM Moniker (P01 (includes P59), P04, P08, etc...)
        # 2: Kernel Base Address
        # 3: Loader Base Address or NOLOADER if a loader is not used.
        #
        for p in "P01 FF8000 NOLOADER" "P04 FF8000 FF9890" "P04_Early FF8000 NOLOADER" "P05 FFC100 NOLOADER" "P08 FFAC00 NOLOADER" "P10 FFB800 NOLOADER" "P11 FFC100 NOLOADER" "E54 FF9100 NOLOADER" "BlackBox FFC300 NOLOADER"; do
          pcm="${p%% *}";
          p="${p#* }"
          address="${p%% *}"
          p="${p#* }"
          loader="${p%% *}"

          echo "Building Kernel :    ${pcm}"
          make -f makefile-assembly PREFIX=/usr/bin/m68k-linux-gnu- pcm=${pcm} address=${address}
          echo "    Copy-Item Kernel-${pcm}.bin to TemporaryArtifactStorage"
          cp Kernel-${pcm}.bin ../TemporaryArtifactStorage/
          echo "    Cleanup after Kernel-${pcm}"
          echo
          make -f makefile-assembly clean
          #
          # Build the Loader if requested
          #
          if [ ${loader} != NOLOADER ]; then
            echo "Building Loader :    ${pcm}"
            make -f makefile-assembly PREFIX=/usr/bin/m68k-linux-gnu- pcm=${pcm} address=${loader} name=Loader
            echo "    Copy-Item Loader-${pcm}.bin to TemporaryArtifactStorage"
            cp Loader-${pcm}.bin ../TemporaryArtifactStorage/
            echo "    Cleanup after Loader-${pcm}"
            echo
            make -f makefile-assembly clean
          fi
        done

    - name: Verify Kernel SHA256
      run: |
        cd TemporaryArtifactStorage
        cat > sha256sums.txt <<'EOF'
        83a99daece53fc7f2e8f21a392a137f1a326b9e83d0371334b183917d7f83c2a  Kernel-BlackBox.bin
        08a0c6e0b90740e13ac6c525292fb17200af577d79387c32bc14336a7da86b60  Kernel-E54.bin
        bb7ae5856741202cc55d45eb73aae5dccfef5ab1cfcb3a88efb73fd1814fd2cf  Kernel-P01.bin
        1e9a119513895830fb00ce136d17149a751f590b8cc313fd68533e8cdb794ed7  Kernel-P04.bin
        85e58aa9af3ca97acbcd70a476409d9e81703defd0b1a2e8f0917aee100b916c  Kernel-P04_Early.bin
        966d9cd2ebac79eccd4178f7661d48f789691602cd92a69efba75ed2327debf7  Kernel-P05.bin
        e5f15e8cb91d2e57ed5b5722b8a6ee37b939a5c26e187eeb6a9920a9906bf372  Kernel-P08.bin
        0824c10c88ab5f097545684ca46b9f4d75ecf23a23fb0542e40945cdbb71c63a  Kernel-P10.bin
        2fc2233e094eebad4eeedb41cc7de4dd7e9f039b9575cbcecc3c6f0356185f42  Kernel-P11.bin
        868ccae5858919d22d67ad6d477549b91d6a786490128a3dd7338ea6a52fc7cd  Kernel-P12.bin
        48b0d3d29fd7a8514f85dc20174d94f19cb19095189f0e8b04650747f4c9bac7  Loader-P04.bin
        EOF
        sha256sum -c sha256sums.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Kernels_${{github.sha}}
        path: TemporaryArtifactStorage

  PCMHammer:
    needs: Kernels
    runs-on: windows-2025
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.7

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v2.0.0

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore NuGet Packages
      run: nuget restore Apps/PcmApps.sln

    - name: Download Kernels artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: Kernels_${{github.sha}}
        path: TemporaryArtifactStorage

    - name: Remove Stale Kernels artifact
      uses: geekyeggo/delete-artifact@v5.1.0
      with:
        name: Kernels_${{github.sha}}

    - name: Fetch .Net 4.6.2
      run: |
        Invoke-WebRequest https://go.microsoft.com/fwlink/?linkid=2099466 -OutFile .\NDP462-DevPack-KB3151934-ENU.exe
        .\NDP462-DevPack-KB3151934-ENU.exe /passive /norestart

    - name: Build Applications
      run: msbuild Apps/PcmApps.sln

    - name: Add PCM Hammer to temporary artifact storage
      run: |
        Copy-Item -Path "Apps/PcmHammer/bin/Debug/PcmHammer.*" -Destination TemporaryArtifactStorage
        Copy-Item -Path "Apps/PcmHammer/bin/Debug/*.dll" -Destination TemporaryArtifactStorage
        Copy-Item -Path "Apps/PcmHammer/bin/Debug/*.pdb" -Destination TemporaryArtifactStorage

    - name: Add PCM Logger to temporary artifact storage
      run: |
        Copy-Item -Path "Apps/PcmLogger/bin/Debug/PcmLogger.*" -Destination TemporaryArtifactStorage
        Copy-Item -Path "Apps/PcmLogger/bin/Debug/*.dll" -Destination TemporaryArtifactStorage
        Copy-Item -Path "Apps/PcmLogger/bin/Debug/*.pdb" -Destination TemporaryArtifactStorage
        Copy-Item -Path "Apps/PcmLogger/*.LogProfile" -Destination TemporaryArtifactStorage
        Copy-Item -Path "Apps/PcmLogger/Parameters.*.xml" -Destination TemporaryArtifactStorage

    - name: Add VPW Explorer to temporary artifact storage
      run: |
        Copy-Item -Path "Apps/VpwExplorer/bin/Debug/VpwExplorer.*" -Destination TemporaryArtifactStorage
        Copy-Item -Path "Apps/VpwExplorer/bin/Debug/*.dll" -Destination TemporaryArtifactStorage
        Copy-Item -Path "Apps/VpwExplorer/bin/Debug/*.pdb" -Destination TemporaryArtifactStorage

    - name: Is it all there ??
      run: ls -l TemporaryArtifactStorage/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.4.0
      with:
        name: PCMHacks_${{github.sha}}
        path: TemporaryArtifactStorage
